#karas = 2.0.2
#tensorflow = 1.0.1
#use cpu

FROM citcailearning/scipy_notebook:ubuntu16.04

MAINTAINER Mad Chang <citcailearning@gmail.com>

RUN /opt/conda/bin/pip install tensorflow==1.0.1
RUN /opt/conda/bin/pip install keras==2.0.2

USER $NB_USER
